apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-http"
  labels:
    app: "{{ .Release.Name }}-http"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 47334
      protocol: TCP
      name: http
  selector:
    app: "{{ .Release.Name }}"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mysql"
  labels:
    app: "{{ .Release.Name }}-mysql"
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 47335
      protocol: TCP
      name: http
  selector:
    app: "{{ .Release.Name }}"
