apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
    port: 7880
    rtc:
      tcp_port: 7881
      port_range_start: {{ .Values.livekit.udpPortRange.start }}
      port_range_end: {{ .Values.livekit.udpPortRange.end }}
      use_external_ip: false
      node_ip: {{ .Values.livekit.nodeIp | quote }}
      use_ice_lite: true
    logging:
      level: info
      json: true
    room:
      auto_create: true
      empty_timeout: 300
      departure_timeout: 20
