apiVersion: v1
kind: Service
metadata:
  name: audiocpp
  namespace: prod
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  clusterIP: None
  type: ClusterIP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: audiocpp
  namespace: prod
  labels:
    kubernetes.io/service-name: audiocpp
  annotations:
    argocd.argoproj.io/sync-options: Prune=false;ServerSideApply=true
addressType: IPv4
endpoints:
  - addresses:
      - "192.168.10.197"
ports:
  - port: 8081
    protocol: TCP
