apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-nginx-config"
data:
  default.conf: |
    upstream wger {
      server localhost:8000;
    }

    map $http_x_forwarded_proto $proto {
      default $http_x_forwarded_proto;
      ''      $scheme;
    }

    server {
      listen 80;

      location / {
        proxy_pass http://wger;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $proto;
        proxy_set_header X-Forwarded-Host $host;
        proxy_redirect off;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
      }

      location /static/ {
        alias /wger/static/;
        expires 1y;
        add_header Cache-Control "public, immutable";
      }

      location /media/ {
        alias /wger/media/;
      }

      client_max_body_size 100M;
    }
