image:
  repository: codeberg.org/readeck/readeck
  tag: latest@sha256:13fc370031543af7de0dbab84b3476ade6b77570e8dfffddbebdd7bfb8ffb387
  pullPolicy: IfNotPresent

subdomain: readeck

# Deployment configuration
deployment:
  strategy: Recreate
  replicas: 1

# Container configuration
container:
  port: 8000
  healthProbe:
    type: tcpSocket
    port: http # Use named port

# Service configuration
service:
  port: 80
  type: ClusterIP

# Volume configuration
volumes:
  - name: data
    mountPath: /readeck
    persistentVolumeClaim: data

# Persistent volume claims
persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: true

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: true
    private: true

# Environment variables
env:
  TZ:
    value: "{timezone}"
  READECK_SERVER_HOST: "0.0.0.0"
