image:
  repository: ollama/ollama
  tag: 0.23.3@sha256:9b519ed11930ba9a3c6123f8546b8f553e247ea6ce58739a4878f913996e7a67
  pullPolicy: IfNotPresent

subdomain: ollama

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 11434
  healthProbe:
    type: tcpSocket
  resources:
    limits:
      gpu.intel.com/i915: "1"
    requests:
      gpu.intel.com/i915: "1"

service:
  port: 80

volumes:
  - name: data
    mountPath: /root/.ollama
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: false

virtualService:
  enabled: true
  gateways:
    public: false
    private: true

env:
  OLLAMA_INTEL_GPU: "true"
