image:
  repository: ollama/ollama
  tag: 0.17.7@sha256:0ff452f6a4c3c5bb4ab063a1db190b261d5834741a519189ed5301d50e4434d1
  pullPolicy: IfNotPresent

subdomain: ollama

deployment:
  strategy: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 11434
  healthProbe:
    type: tcpSocket
  resources:
    limits:
      gpu.intel.com/i915: "1"
    requests:
      gpu.intel.com/i915: "1"

service:
  port: 80

volumes:
  - name: data
    mountPath: /root/.ollama
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path

virtualService:
  enabled: true
  gateways:
    public: true
    private: false

env:
  OLLAMA_INTEL_GPU: "true"
