image:
  repository: ollama/ollama
  tag: 0.21.1@sha256:cd33c5656285ca365c9c5495fe0240a70aef642088c6427c461fd54b62f80ffb
  pullPolicy: IfNotPresent

subdomain: ollama

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 11434
  healthProbe:
    type: tcpSocket
  resources:
    limits:
      gpu.intel.com/i915: "1"
    requests:
      gpu.intel.com/i915: "1"

service:
  port: 80

volumes:
  - name: data
    mountPath: /root/.ollama
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: false

virtualService:
  enabled: true
  gateways:
    public: false
    private: true

env:
  OLLAMA_INTEL_GPU: "true"
