apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-redis"
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-redis"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-redis"
    spec:
      containers:
        - name: "{{ .Release.Name }}-redis"
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: "{{ .Values.redis.image.pullPolicy }}"
          ports:
            - name: tcp
              containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
          livenessProbe:
            tcpSocket:
              port: tcp
          readinessProbe:
            tcpSocket:
              port: tcp
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-redis-data"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-redis"
  labels:
    app: "{{ .Release.Name }}-redis"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: tcp
  selector:
    app: "{{ .Release.Name }}-redis"
