apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.agent.pipelineNamespace }}"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pipeline-defaults
  namespace: "{{ .Values.agent.pipelineNamespace }}"
spec:
  limits:
    - type: Container
      default:
        {{- toYaml .Values.agent.pipelineLimits.default | nindent 8 }}
      defaultRequest:
        {{- toYaml .Values.agent.pipelineLimits.defaultRequest | nindent 8 }}
