---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-pull-secret
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgAWrY013uj3tp5zRs6k8kCJPXGjJjon21rxPFlacvJQs2+K9ar83PNFKtZiIAk+W9jZDzJBa47xxumvNYAze98N1SJUW3rfAaZc0mEsZM7YV/8/+yOC3tazLF0hOn0Scl5CjuNZbtyENNTUGSiqXcsWwzzYKbmq8W3AzH/QRSRYIE+bnzX/JewsaBbMsH0txxyAJ4Haiglij+z+kWarq9WWwmBxe2xhbxVHLsfGI9DpUoBX7mSBbyX5GWkyiwVDCs7CYHLJdc6xMR9etVnshVbSKIXnxZlZvUt8pHIcimc+CVUmUyFpRYYQws4ao3OFQ72HkGvk5IGXRYbdophHY9cggiEmzO2aKrBmDvVc6LXjCMq69KWs0suIyFJQRro/RJZ4TgmEPseiI6ptEt82JVN2iHamDJoWnNu44VtRrhuqQPaaQBk6Vbm5RaGoqQ9sZ12xGCQk1tpCjRigdBWuMS0DpseRXhJDjyuOTZ/oZUXaZhYqajoIPIM6pvBnNxP9vgQJ4NqbSss9cGgvqula6FoTqEFefVysYnLW0EdqXix9SHDjz+bCtc5BrupNUC39vemVhFa8NeaGEPD+lZSt8JqyC4AumlCV4c8GD5fiCKWKF4odLINTkmgkVM90+uaj2yKLG1Y5EppXhwuKFp4TjSGKBqa8kvc/VCwv9b8oZ9zJbN6YKbgtVhF5t7OP9kHfo7UUd5SE80k3AByBHHdQYcAkvc1f8R2EMddzYVh1vGd7Ie0j60vKJgAVzFOm07oqV5f0juUgeFYm1QA2M6h/DYlfPPPwtNg0Iq2SOmjhHXYcWG5aj2qfBgrz0hU4bIentQ==
  template:
    metadata:
      name: woodpecker-pull-secret
      namespace: prod
    type: kubernetes.io/dockerconfigjson
