---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-pull-secret
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgCAGlxDu7a6JW8vV56z+owXaUKDbyaSysUsNvGYqvEisiVTcrn44yUlJjzZhMCStJTB5Vaf9U0veSyJKD59ERkij1duvrMsLuCC/1xJxQnWuWWsGchiYJ3bGUq8n+miVlETKnQ1dYfBHDneU6WU1qTHId6un+sCy6S+ToXeFDsQ16KRBlI2ZjKNXowTH1fjjefvYL0JhxdeMNtc63b7Z58FG7QipTt4vEWkpfzu0NTEmsA5JYgDuQI2iCXHJIE1TuBTLYTEYGmmGz8P9ztayQdRLvV3vh+waNAg3VbIbZItFm3JrKAlwbcBw/Vfh+2BUl5VIehrjfI/e+FCz3pHJYqq9moK5JAv4Heok77Y6d8zv/PkBhhZcSkWVMaG2peBUDmsRf8Zyc9uC3jtsY3fxoGhyF7CV2aCKiMLatHfzYqcNfkNi7MyAwrRPagyZfsX76WMPZ7DlFHW3tBRc91vQZTZUvM8sOy3xcBCyD5mbqPAgpuaIk6tshvJXwwWeFv9haoZJgQMctQ3cBR2OKUAUyGQ9belHpPfmoSPa1v11QkThDSh7ZuX3C1nnhk95nP0OgZCwb/cIvPA+vcETDKIqj/hfF8oloKSkMgGtE+XGB813VxTbhBhKD8ETD3zzFY6zqOhwMICTXhi9plcMxCDIkg8R32ZqXbAvuK3BeDe9TwDh7ksLlKICWvlUEvWKshAUvjgwyUc0uiS2aHu8lvQDiKOmESmimk6NmVtSfvgkSOJl255BoaIvLGiF8/i2R2Bt9yAF11dqEMytWX6XP3odyH2AYtGveJysarN7msnJIYcbnO3/bc1e3pVKnoKtdIz6wd9wN2D1gfMzghgxuxZiHoeH8I=
  template:
    metadata:
      name: woodpecker-pull-secret
      namespace: prod
    type: kubernetes.io/dockerconfigjson
