---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-pull-secret
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgBKVmEVGq5DyzTCblSwv9XQV8HqoSiZTavblvNF369PiaOX3eTgavzZ49SJzXkNUkgUxGYsntHiQGhj+7wXEVEWSFuvm2z6rusFjDOeLNtqxqar8gU1cKOYElMWPAIP3fjZEEaxwUTrH8gnTNgPwIQmtuoPgkpR1JbIs4nrjfsjtmExkiaoj8LQK08yi75d6fOiPuaoyvhqNoA/VGAmAU+09/3SneyIt8eMS/dpN2eqVnnihbE+HhvOX0SKHeAa9MM2TJEYm4Tkf63RBVike5zNjVEyxlGn6ENjLjUKe1ROuZXrl1s3kalGW/Z0sWsiwgpm0rGgOGm8IslYkgBxNi9TCpdj+LD9+tK3pzLOSgztjC2iSOwbGs6+BdaBfzcVmg6yfmzJ0kkkSbhbuQ2AFHoQ29SBM/k3Q8X2MWmBlKiVRLsIF6y8L5zgEaD/mR4UeyL6mQEY/nBbN+zNY2yEM8TQKz//7HfYC5XFcvjkOmgdCGHf6JX1Gd9bTleXMlyfwSHEkA8mRgmZviR/cvlWn76eF9mMlk3Td6K2thGkAb0F0C4QR5aI00cB8HbXBM7cAZx8mo0Lz33AiJt6qXOveBN+XusAx8xPh/IK6PpMXCNJJvrLyGtNafpawsmOWyJisg4ryGPCtC8IwDwnFyXHViE/RYbBjcwi/zzkULkG7dughFZA4rLDjAhVPvp+cyaun8KB4aLhHrc3jVmRbYaBrNDPThtnryO+75LXa1/OcOgrCaXFAdtUaWip9V4+27IzgJrfO0G3T7b2NzWRxhHVN89hrfpqTEGI9LjDlM2OwoM5bQkFV7+x4oeYHlShttW14h1Z5trX592A/amyQPZT+ApA1OyS1ruTnknrnvTeCSx0aPn1SVO/1ng/lm7XklLLgfGMUMLU71ysgQZIjs26UNY1+GccLRK5fjIDKml/4zp2VSxJmVC7yu1cW2TtVFe6VMOOLA==
  template:
    metadata:
      name: woodpecker-pull-secret
      namespace: prod
    type: kubernetes.io/dockerconfigjson
