image:
  repository: code.olsen.cloud/incubator/grundlag
  tag: latest@sha256:979d5ec0cfddcb1b7a13c90bebafdab48466d1c45a721e432d58e6fb3475772d
  pullPolicy: IfNotPresent

subdomain: grundlag

volumes:
  - name: data
    mountPath: /data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 5Gi
    storageClassName: local-path
    backup: true

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 3800
  healthProbe:
    type: httpGet
    path: /api/health
    port: 3800
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 6
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi

service:
  port: 80
  type: ClusterIP

virtualService:
  enabled: true
  gateways:
    public: false
    private: true

env:
  HA_URL:
    valueFrom:
      secretKeyRef:
        name: grundlag-secrets
        key: HA_URL
  HA_TOKEN:
    valueFrom:
      secretKeyRef:
        name: grundlag-secrets
        key: HA_TOKEN
