globals:
  environment: prod
  domain: olsen.cloud
  timezone: Europe/Amsterdam
image:
  repository: ghcr.io/linkwarden/linkwarden
  tag: v2.13.0@sha256:bd3565d3f13c2d590f417710819f4c6b4fe19f8b841fc45ab3fe4c61ba12d34f
  pullPolicy: IfNotPresent
subdomain: linkwarden
