image:
  repository: vaultwarden/server
  tag: 1.36.0@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
  pullPolicy: IfNotPresent

subdomain: vaultwarden

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 80
  healthProbe:
    type: tcpSocket

service:
  port: 80

volumes:
  - name: data
    mountPath: /data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 3Gi
    storageClassName: local-path
    backup: true

virtualService:
  enabled: true
  gateways:
    public: true
    private: true

env:
  DOMAIN:
    value: "https://{subdomain}.{domain}"

