image:
  repository: vaultwarden/server
  tag: 1.37.4@sha256:efb3cde962015fcc036b2ea625242248611943b27212ebf4392841fb30fad055
  pullPolicy: IfNotPresent

subdomain: vaultwarden

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 80
  healthProbe:
    type: tcpSocket

service:
  port: 80

volumes:
  - name: data
    mountPath: /data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 3Gi
    storageClassName: local-path
    backup: true

virtualService:
  enabled: true
  gateways:
    public: true
    private: true

env:
  DOMAIN:
    value: "https://{subdomain}.{domain}"

