image:
  repository: vaultwarden/server
  tag: 1.35.7@sha256:9a8eec71f4a52411cc43edc7a50f33e9b6f62b5baca0dd95f0c6e7fd60f1a341
  pullPolicy: IfNotPresent

subdomain: vaultwarden

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 80
  healthProbe:
    type: tcpSocket

service:
  port: 80

volumes:
  - name: data
    mountPath: /data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 3Gi
    storageClassName: local-path
    backup: true

virtualService:
  enabled: true
  gateways:
    public: true
    private: true

env:
  DOMAIN:
    value: "https://{subdomain}.{domain}"

