apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configfile"
data:
  config.yml: |
    filesystem:
      roms_folder: "Roms"

    platforms:
      FC:
        slug: famicom
      SFC:
        slug: snes
      MD:
        slug: genesis
      MS:
        slug: sms
      PCE:
        slug: tg16
      PS:
        slug: psx
      NGP:
        slug: neo-geo-pocket
      WS:
        slug: wonderswan
      NEOGEO:
        slug: neogeoaes
      NP2KAI:
        slug: pc-9800-series
      MAME2003PLUS:
        slug: arcade
      MAME2010:
        slug: arcade
