---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .Release.Name }}-api-key-generator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  length: 48
  allowRepeat: true
  encoding: base64url
  secretKeys:
    - apiKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  refreshInterval: "0"
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        apiKey: "{{ `{{ .apiKey }}` }}"
        terminalServerConnections: >-
          [{"id":"open-terminal","name":"Open Terminal","enabled":true,"url":"http://open-terminal.{{ .Release.Namespace }}.svc.cluster.local","path":"/openapi.json","key":"{{ `{{ .apiKey }}` }}","auth_type":"bearer","server_type":"terminal"}]
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ .Release.Name }}-api-key-generator
