image:
  repository: apache/tika
  tag: 3.3.1.0-full@sha256:d8e6ed96260ad89307a93195a1b856102987a818ac648502f8efbaf313d32470
  pullPolicy: IfNotPresent

subdomain: tika

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 9998
  healthProbe:
    type: tcpSocket

service:
  port: 80

virtualService:
  enabled: false
