image:
  repository: apache/tika
  tag: 3.3.0.0-full@sha256:ecdd37e204308266b1f8e28569f8516ebd5b96d7a4518a71d3904710b20c03b3
  pullPolicy: IfNotPresent

subdomain: tika

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 9998
  healthProbe:
    type: tcpSocket

service:
  port: 80

virtualService:
  enabled: false
