image:
  repository: docker.umami.is/umami-software/umami
  tag: postgresql-latest@sha256:e3f80c0625aad7179b49da27d475357cabb1068b8cacd9a792cfd6966888b123
  pullPolicy: IfNotPresent

subdomain: umami

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

# Deployment configuration
deployment:
  strategy: RollingUpdate
  replicas: 1

# Container configuration
container:
  port: 3000
  healthProbe:
    type: tcpSocket
    port: http # Use named port

# Service configuration
service:
  port: 80
  type: ClusterIP

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: true
    private: true

# Database configuration
database:
  enabled: true

# External Secrets configuration
externalSecrets:
  - name: "{release}-secrets"
    passwords:
      - name: encryptionkey
        length: 64
        allowRepeat: true
        encoding: hex
        secretKeys:
          - encryptionkey

# Environment variables
env:
  TZ:
    value: "{timezone}"
  DISABLE_TELEMETRY: "1"
  APP_SECRET:
    valueFrom:
      secretKeyRef:
        name: "{release}-secrets"
        key: encryptionkey
  DATABASE_URL:
    valueFrom:
      secretKeyRef:
        name: "{release}-connection"
        key: url
