apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-server"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-server"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-server"
    spec:
      initContainers:
        - name: db-migrate
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          command: ["/opt/netbox/docker-entrypoint.sh"]
          args: ["python", "/opt/netbox/netbox/manage.py", "migrate", "--no-input"]
          env:
{{ include "netbox.env" . | indent 12 }}
      containers:
        - name: "{{ .Release.Name }}-server"
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          env:
{{ include "netbox.env" . | indent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/netbox/netbox/media
              name: media
            - mountPath: /opt/netbox/netbox/reports
              name: reports
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-media"
        - name: reports
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-reports"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-worker"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-worker"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-worker"
    spec:
      containers:
        - name: "{{ .Release.Name }}-worker"
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          command: ["/opt/netbox/venv/bin/python"]
          args: ["/opt/netbox/netbox/manage.py", "rqworker"]
          env:
{{ include "netbox.env" . | indent 12 }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command: ["pgrep", "-f", "rqworker"]
            periodSeconds: 30
          volumeMounts:
            - mountPath: /opt/netbox/netbox/media
              name: media
            - mountPath: /opt/netbox/netbox/reports
              name: reports
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-media"
        - name: reports
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-reports"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-housekeeping"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-housekeeping"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-housekeeping"
    spec:
      containers:
        - name: "{{ .Release.Name }}-housekeeping"
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          command: ["/opt/netbox/venv/bin/python"]
          args: ["/opt/netbox/netbox/manage.py", "housekeeping"]
          env:
{{ include "netbox.env" . | indent 12 }}
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-redis"
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-redis"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-redis"
    spec:
      containers:
        - name: "{{ .Release.Name }}-redis"
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: "{{ .Values.redis.image.pullPolicy }}"
          ports:
            - name: tcp
              containerPort: 6379
              protocol: TCP
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
          livenessProbe:
            tcpSocket:
              port: tcp
          readinessProbe:
            tcpSocket:
              port: tcp
