subdomain: immich

# Image configurations for multiple deployments
server:
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: release@sha256:6c011eaa315b871f3207d68f97205d92b3e600104466a75b01eb2c3868e72ca1
    pullPolicy: IfNotPresent
ml:
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    tag: release@sha256:5fee7f3e052c3d32d4edecafad68317394daae26f57d895fbd487886083725a7
    pullPolicy: IfNotPresent
valkey:
  image:
    repository: valkey/valkey
    tag: 9-alpine@sha256:c106a0c03bcb23cbdf9febe693114cb7800646b11ca8b303aee7409de005faa8
    pullPolicy: IfNotPresent
postgres:
  image:
    repository: pgvector/pgvector
    tag: pg16@sha256:0a07c4114ba6d1d04effcce3385e9f5ce305eb02e56a3d35948a415a52f193ec
    pullPolicy: IfNotPresent

# Database configuration
database:
  enabled: true

# Persistent volume claims
persistentVolumeClaims:
  - name: upload
    size: 100Gi
    storageClassName: persistent
  - name: library
    size: 100Gi
    storageClassName: persistent
  - name: model-cache
    size: 10Gi

# Note: Services are kept custom due to different selectors for each deployment

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: true
    private: true
  servicePort: 80 # Port of the main server service

# OIDC client configuration
oidc:
  enabled: true
  redirectUris:
    - "/api/auth/callback/authentik"
  subjectMode: user_username
