subdomain: immich

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

# Image configurations for multiple deployments
server:
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: release@sha256:79cc1623323d5894922686d8743b4780181428f98eecbfb58ce12c41ef02d1ea
    pullPolicy: IfNotPresent
ml:
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    tag: release@sha256:60dfcf266a9ef3b7376f5678e8c980d4fb61db5fc48c078fe8a326ab1535d60d
    pullPolicy: IfNotPresent
valkey:
  image:
    repository: valkey/valkey
    tag: 9-alpine@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11
    pullPolicy: IfNotPresent
postgres:
  image:
    repository: pgvector/pgvector
    tag: pg16@sha256:ccc6e83d6e35e931dc7c5def2022729d5a6c370318d099181995567ff1fb4d6b
    pullPolicy: IfNotPresent

# Database configuration
database:
  enabled: true

# Persistent volume claims
persistentVolumeClaims:
  - name: upload
    size: 100Gi
    storageClassName: local-path
    backup: true
  - name: library
    size: 100Gi
    storageClassName: local-path
    backup: true
  - name: model-cache
    size: 10Gi
    storageClassName: local-path
    backup: false

# Note: Services are kept custom due to different selectors for each deployment

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: true
    private: true
  servicePort: 80 # Port of the main server service

# OIDC client configuration
oidc:
  enabled: true
  redirectUris:
    - "/api/auth/callback/authentik"
  subjectMode: user_username
