subdomain: immich

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

# Image configurations for multiple deployments
server:
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: release@sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb
    pullPolicy: IfNotPresent
ml:
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    tag: release@sha256:5a0839dc5303cd7215bcd2180a26aed3af41675aefb3e75e5157e9f10ad16e6e
    pullPolicy: IfNotPresent
valkey:
  image:
    repository: valkey/valkey
    tag: 9-alpine@sha256:15568b9cb7eb67f4aed4de018c23f13d344e0e6437b31fe8fb8823dc81ebb3a9
    pullPolicy: IfNotPresent
postgres:
  image:
    repository: pgvector/pgvector
    tag: pg16@sha256:ccc6e83d6e35e931dc7c5def2022729d5a6c370318d099181995567ff1fb4d6b
    pullPolicy: IfNotPresent

# Database configuration
database:
  enabled: true

# Persistent volume claims
persistentVolumeClaims:
  - name: upload
    size: 100Gi
    storageClassName: local-path
    backup: true
  - name: library
    size: 100Gi
    storageClassName: local-path
    backup: true
  - name: model-cache
    size: 10Gi
    storageClassName: local-path
    backup: false

# Note: Services are kept custom due to different selectors for each deployment

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: true
    private: true
  servicePort: 80 # Port of the main server service

# OIDC client configuration
oidc:
  enabled: true
  redirectUris:
    - "/api/auth/callback/authentik"
  subjectMode: user_username
