apiVersion: postgres.homelab.mortenolsen.pro/v1
kind: PostgresDatabase
metadata:
  name: "{{ .Release.Name }}-history"
  namespace: "{{ .Release.Namespace }}"
spec:
  clusterRef:
    name: "{{ .Values.postgresCluster.name }}"
    namespace: "{{ .Values.postgresCluster.namespace }}"
---
apiVersion: postgres.homelab.mortenolsen.pro/v1
kind: PostgresDatabase
metadata:
  name: "{{ .Release.Name }}-visibility"
  namespace: "{{ .Release.Namespace }}"
spec:
  clusterRef:
    name: "{{ .Values.postgresCluster.name }}"
    namespace: "{{ .Values.postgresCluster.namespace }}"
