image:
  repository: gotson/komga
  tag: latest@sha256:e109902ebebb8a05f633f48d84a2ac7bb1334bf0f6fbc17262a333082c7de44d
  pullPolicy: IfNotPresent

subdomain: komga

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1

container:
  port: 25600
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  healthProbe:
    type: tcpSocket
    port: "25600"

service:
  port: 80
  targetPort: 25600
  type: ClusterIP

volumes:
  - name: config
    mountPath: /config
    persistentVolumeClaim: komga-config
  - name: comics
    mountPath: /data/comics
    persistentVolumeClaim: comics
  - name: downloads
    mountPath: /data/downloads
    persistentVolumeClaim: downloads

persistentVolumeClaims:
  - name: config
    size: 1Gi
    storageClassName: local-path
    backup: true

initContainers:
  - name: fix-permissions
    image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
    command: ["sh", "-c", "chown -R 1000:1000 /config"]
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: config
        mountPath: /config

virtualService:
  enabled: true
  gateways:
    public: true
    private: true
