image:
  repository: gotson/komga
  tag: latest@sha256:c4f9885fc077e2e9cd684dc95e8f6cfa5e33b100b46712b2de7f5cc2ff59e6fb
  pullPolicy: IfNotPresent

subdomain: komga

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1

container:
  port: 25600
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  healthProbe:
    type: tcpSocket
    port: "25600"

service:
  port: 80
  targetPort: 25600
  type: ClusterIP

volumes:
  - name: config
    mountPath: /config
    persistentVolumeClaim: komga-config
  - name: comics
    mountPath: /data/comics
    persistentVolumeClaim: comics
  - name: downloads
    mountPath: /data/downloads
    persistentVolumeClaim: downloads

persistentVolumeClaims:
  - name: config
    size: 1Gi
    storageClassName: local-path
    backup: true

initContainers:
  - name: fix-permissions
    image: busybox@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
    command: ["sh", "-c", "chown -R 1000:1000 /config"]
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: config
        mountPath: /config

virtualService:
  enabled: true
  gateways:
    public: true
    private: true
