image:
  repository: gotson/komga
  tag: latest@sha256:9cf102f5fb78e2e020700c53eca757e4f4d4e347121b0a16380822760337cca9
  pullPolicy: IfNotPresent

subdomain: komga

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1

container:
  port: 25600
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  healthProbe:
    type: tcpSocket
    port: "25600"

service:
  port: 80
  targetPort: 25600
  type: ClusterIP

volumes:
  - name: config
    mountPath: /config
    persistentVolumeClaim: komga-config
  - name: comics
    mountPath: /data/comics
    persistentVolumeClaim: comics
  - name: downloads
    mountPath: /data/downloads
    persistentVolumeClaim: downloads

persistentVolumeClaims:
  - name: config
    size: 1Gi
    storageClassName: local-path
    backup: true

initContainers:
  - name: fix-permissions
    image: busybox@sha256:fd7dc98638c8e305f4dc34e979f1c0fdfdcaeb0fbf8fcff77ae834b6da3d7e6e
    command: ["sh", "-c", "chown -R 1000:1000 /config"]
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: config
        mountPath: /config

virtualService:
  enabled: true
  gateways:
    public: true
    private: true
