{{- define "apps.freshrss.values" }}
domain: {{ .Values.domain }}
image: lscr.io/linuxserver/freshrss:1.23.1
volumes:
  data:
    config:
      path: /config
env:
  TZ: 'Europe/Amsterdam'
  PUID: '1000'
  PGID: '911'
ingress:
  http:
    containerPort: 80
    subdomain: freshrss
{{- end }}

{{- $value := include "apps.freshrss.values" . | fromYaml }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  project: {{ .Values.namespace }}
  source:
    path: charts/apps/standard
    repoURL: "{{ .Values.baseRepo }}"
    helm:
      values: {{ $value | toJson | quote }}
    targetRevision: "{{ .Values.baseRevision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
