{{- define "apps.ntfy.values" }}
domain: {{ .Values.domain }}
{{- end }}

{{- $value := include "apps.ntfy.values" . | fromYaml }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  project: {{ .Values.namespace }}
  source:
    path: charts/ntfy
    repoURL: "{{ .Values.repo }}"
    helm:
      values: {{ $value | toJson | quote }}
    targetRevision: "{{ .Values.revision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
