apiVersion: v1
kind: Service
metadata:
  name: lmstudio
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.externalService.port }}
      targetPort: {{ .Values.externalService.port }}
  clusterIP: None
  type: ClusterIP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: lmstudio
  namespace: {{ .Release.Namespace }}
  labels:
    kubernetes.io/service-name: lmstudio
  annotations:
    argocd.argoproj.io/sync-options: Prune=false;ServerSideApply=true
addressType: IPv4
endpoints:
  - addresses:
      - "{{ .Values.externalService.ip }}"
ports:
  - port: {{ .Values.externalService.port }}
    protocol: TCP
