image:
  repository: ghcr.io/esphome/esphome
  tag: 2026.6.5@sha256:ffe23402d169fc9b8ff29fc3c9fc13b3c47e8a53726fce4569e2280bd534c84c
  pullPolicy: IfNotPresent

subdomain: esphome

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

# Deployment configuration
deployment:
  strategy: Recreate
  replicas: 1
  hostNetwork: true # ESPHome needs hostNetwork for device discovery

# Container configuration
container:
  port: 6052
  healthProbe:
    type: tcpSocket
    port: http # Use named port

# Service configuration
service:
  port: 80
  type: ClusterIP

# Volume configuration
volumes:
  - name: data
    mountPath: /config
    persistentVolumeClaim: data

# Persistent volume claims
persistentVolumeClaims:
  - name: data
    size: 10Gi
    storageClassName: local-path
    backup: true

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: false
    private: true
