image:
  repository: ghcr.io/esphome/esphome
  tag: 2026.4.5@sha256:7419641c7fd8e37d6362f71c458bb17570f1f471cfea3b022b30dfd8117a2361
  pullPolicy: IfNotPresent

subdomain: esphome

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

# Deployment configuration
deployment:
  strategy: Recreate
  replicas: 1
  hostNetwork: true # ESPHome needs hostNetwork for device discovery

# Container configuration
container:
  port: 6052
  healthProbe:
    type: tcpSocket
    port: http # Use named port

# Service configuration
service:
  port: 80
  type: ClusterIP

# Volume configuration
volumes:
  - name: data
    mountPath: /config
    persistentVolumeClaim: data

# Persistent volume claims
persistentVolumeClaims:
  - name: data
    size: 10Gi
    storageClassName: local-path
    backup: true

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: false
    private: true
