image:
  repository: ghcr.io/esphome/esphome
  tag: 2026.5.2@sha256:d2c415e4b44bd858d18ea09c4e9db6f03f2367a769cd07f92e7c6f7ff52a7ee8
  pullPolicy: IfNotPresent

subdomain: esphome

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

# Deployment configuration
deployment:
  strategy: Recreate
  replicas: 1
  hostNetwork: true # ESPHome needs hostNetwork for device discovery

# Container configuration
container:
  port: 6052
  healthProbe:
    type: tcpSocket
    port: http # Use named port

# Service configuration
service:
  port: 80
  type: ClusterIP

# Volume configuration
volumes:
  - name: data
    mountPath: /config
    persistentVolumeClaim: data

# Persistent volume claims
persistentVolumeClaims:
  - name: data
    size: 10Gi
    storageClassName: local-path
    backup: true

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: false
    private: true
