image:
  repository: ghcr.io/speaches-ai/speaches
  tag: 0.8.3-cpu@sha256:21e3df06d842fb7802ab470dd77c25f0e8c0d22950e8d8c6ae886e851af53ef8
  pullPolicy: IfNotPresent

subdomain: speaches

dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 8000
  healthProbe:
    type: tcpSocket

service:
  port: 80

volumes:
  - name: data
    mountPath: /home/ubuntu/.cache/huggingface/hub
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 50Gi
    storageClassName: local-path
    backup: false

virtualService:
  enabled: true
  gateways:
    public: false
    private: true

env:
  WHISPER__INFERENCE_DEVICE: cpu
  WHISPER__COMPUTE_TYPE: int8
  UVICORN_HOST: 0.0.0.0
