apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: "{{ .Release.Name }}"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mariadb"
  labels:
    app: "{{ .Release.Name }}-mariadb"
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: tcp
  selector:
    app: "{{ .Release.Name }}-mariadb"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-redis"
  labels:
    app: "{{ .Release.Name }}-redis"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: tcp
  selector:
    app: "{{ .Release.Name }}-redis"
