image:
  repository: ghcr.io/open-webui/open-terminal
  tag: 0.11.34@sha256:5e040fe357ce4fbd3d5e59c40247dd32172fa10c51c22ded3a7843e739d06a0e
  pullPolicy: IfNotPresent

subdomain: open-terminal

dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 8000
  healthProbe:
    type: httpGet
    path: /health

service:
  port: 80
  type: ClusterIP

probe:
  path: /health

volumes:
  - name: data
    mountPath: /home/user
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 10Gi
    storageClassName: local-path
    backup: true

virtualService:
  enabled: true
  gateways:
    public: false
    private: true

env:
  OPEN_TERMINAL_API_KEY:
    valueFrom:
      secretKeyRef:
        name: open-terminal-secrets
        key: apiKey
  OPEN_TERMINAL_CORS_ALLOWED_ORIGINS: "https://openwebui.{domain}"
