image:
  repository: ollama/ollama
  tag: 0.32.15@sha256:57d60e686821ea81a7748a3ec8141308c8b8f95b27105713954abf7a6529e700
  pullPolicy: IfNotPresent

subdomain: ollama

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 11434
  healthProbe:
    type: tcpSocket
  resources:
    limits:
      gpu.intel.com/i915: "1"
    requests:
      gpu.intel.com/i915: "1"

service:
  port: 80

volumes:
  - name: data
    mountPath: /root/.ollama
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: false

virtualService:
  enabled: true
  gateways:
    public: false
    private: true

env:
  OLLAMA_INTEL_GPU: "true"
