{{- if and .Values.dns .Values.dns.enabled }}
apiVersion: dns.homelab.mortenolsen.pro/v1alpha1
kind: DNSRecord
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.dns.type | default "A" }}
  domain: {{ .Values.globals.domain }}
  subdomain: {{ .Values.subdomain }}
  {{- if .Values.dns.dnsClassRef }}
  dnsClassRef:
    {{- toYaml .Values.dns.dnsClassRef | nindent 4 }}
  {{- end }}
  values:
    - {{ .Values.globals.networking.private.ip | quote }}
{{- end }}
