apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-notify-config"
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: https://{{ .Values.subdomain }}.{{ .Values.domain }}
    attachment-cache-dir: "/var/lib/ntfy/attachments"
    cache-file: "/var/lib/ntfy/cache.db"
    auth-file: "/var/lib/ntfy/users.db"
    auth-default-access: deny-all
    upstream-base-url: "https://ntfy.sh"
