apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - name: "{{ .Release.Name }}"
          image: binwiederhier/ntfy:v2.11.0
          args: ["serve"]
          ports:
            - name: svc-web
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     port: svc-ui
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     port: svc-ui
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   failureThreshold: 10
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/lib/ntfy/
              name: data 
            - name: config
              mountPath: "/etc/ntfy"
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data"
        - name: config
          configMap:
            name: "{{ .Release.Name }}-notify-config"
