---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: foundation
    server: https://kubernetes.default.svc
  project: foundation
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.26.1
    chart: cloudnative-pg
    helm: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  info:
    - name: "Documentation: "
      value: "https://cloudnative-pg.io/documentation/current/"
