image:
  repository: tailscale/tailscale
  tag: v1.82.5
  pullPolicy: IfNotPresent

subdomain: headscale-router

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  podAnnotations:
    sidecar.istio.io/inject: "false"

container:
  port: 41641
  healthProbe:
    type: tcpSocket
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
        - NET_RAW
  resources:
    limits:
      memory: "128Mi"
      cpu: "250m"

service:
  port: 41641

virtualService:
  enabled: false

env:
  TS_EXTRA_ARGS:
    value: "--login-server=http://headscale.prod.svc.cluster.local"
  TS_ROUTES:
    value: "192.168.10.0/24,192.168.20.0/24,192.168.30.0/24,10.42.0.0/16,10.43.0.0/16"
  TS_STATE_DIR:
    value: "/var/lib/tailscale"
  TS_USERSPACE:
    value: "false"
  TS_ACCEPT_DNS:
    value: "false"
  TS_HOSTNAME:
    value: "k8s-router"
  TS_KUBE_SECRET:
    value: ""
  TS_AUTHKEY:
    valueFrom:
      secretKeyRef:
        name: headscale-router-auth
        key: authkey

volumes:
  - name: data
    mountPath: /var/lib/tailscale
    persistentVolumeClaim: data
  - name: tun
    mountPath: /dev/net/tun
    hostPath: /dev/net/tun
    hostPathType: CharDevice

persistentVolumeClaims:
  - name: data
    size: 100Mi
    storageClassName: local-path
    backup: false
