apiVersion: v2
version: 0.1.0
name: gotosocial
description: Personal single-user GoToSocial fediverse server
dependencies:
  - name: homelab-common
    version: 0.1.8
    repository: https://mortenolsen.pro/homelab-core/
