subdomain: netbox

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

server:
  image:
    repository: netboxcommunity/netbox
    tag: v4.6.0@sha256:bd1f7c2b4ae4ca297e6d56a41ed7b8ae95283a14e5281a2229db72661c3dc9aa
    pullPolicy: IfNotPresent

redis:
  image:
    repository: valkey/valkey
    tag: 9-alpine@sha256:d1cc70645bbcef743615463a2fa4616e841407545e18f560aed0c49671a90147
    pullPolicy: IfNotPresent

database:
  enabled: true

persistentVolumeClaims:
  - name: media
    size: 5Gi
    storageClassName: local-path
    backup: true
  - name: reports
    size: 1Gi
    storageClassName: local-path
    backup: false

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
  servicePort: 80

oidc:
  enabled: true
  redirectUris:
    - "/oauth/complete/oidc/"
  subjectMode: user_username

externalSecrets:
  - name: "{release}-secrets"
    passwords:
      - name: secret-key
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - secret-key
      - name: superuser-password
        length: 32
        encoding: hex
        allowRepeat: true
        secretKeys:
          - superuser-password
      - name: token-pepper
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - token-pepper
