subdomain: netbox

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

server:
  image:
    repository: netboxcommunity/netbox
    tag: v4.5.9@sha256:5e331fb1575c21838af15c4fd59e700488d6253f0f5cacc4b180e422607fa45f
    pullPolicy: IfNotPresent

redis:
  image:
    repository: valkey/valkey
    tag: 9-alpine@sha256:e1095c6c76ee982cb2d1e07edbb7fb2a53606630a1d810d5a47c9f646b708bf5
    pullPolicy: IfNotPresent

database:
  enabled: true

persistentVolumeClaims:
  - name: media
    size: 5Gi
    storageClassName: local-path
    backup: true
  - name: reports
    size: 1Gi
    storageClassName: local-path
    backup: false

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
  servicePort: 80

oidc:
  enabled: true
  redirectUris:
    - "/oauth/complete/oidc/"
  subjectMode: user_username

externalSecrets:
  - name: "{release}-secrets"
    passwords:
      - name: secret-key
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - secret-key
      - name: superuser-password
        length: 32
        encoding: hex
        allowRepeat: true
        secretKeys:
          - superuser-password
      - name: token-pepper
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - token-pepper
