image:
  repository: code.olsen.cloud/incubator/editions
  tag: latest@sha256:dc82c6e52d1bb8081e5e8b4aef64293fc2359f2cb7a3cea241035782cb1011a7
  pullPolicy: Always

subdomain: editions

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1

container:
  ports:
    - name: http
      port: 3007
      protocol: TCP
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
# Service configuration
service:
  port: 3007
  type: ClusterIP

initContainers:
  - name: fix-permissions
    image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
    command: ["sh", "-c", "chown -R 1001:1001 /data"]
    volumeMounts:
      - name: data
        mountPath: /data
    securityContext:
      runAsUser: 0
externalSecrets:
  - name: "{release}-secrets"
    passwords:
      - name: jwt-secret
        length: 48
        encoding: hex
        allowRepeat: true
        secretKeys:
          - jwt-secret

env:
  EDITIONS_PORT: "3007"
  EDITIONS_JWT_SECRET:
    valueFrom:
      secretKeyRef:
        name: "{release}-secrets"
        key: jwt-secret

volumes:
  - name: data
    mountPath: /data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 10Gi
    storageClassName: local-path
    backup: true

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: false
    private: true
