frontend:
  image:
    repository: penpotapp/frontend
    tag: 2.10.0
    pullPolicy: IfNotPresent
  subdomain: penpot
backend:
  image:
    repository: penpotapp/backend
    tag: 2.10.0
    pullPolicy: IfNotPresent
exporter:
  image:
    repository: penpotapp/exporter
    tag: 2.10.0
    pullPolicy: IfNotPresent
valkey:
  image:
    repository: valkey/valkey
    tag: 9.0@sha256:34ecbbe536de15b4750d0c76701eb6b889c6de9b697f782e73165f3ef9cc17c0
    pullPolicy: IfNotPresent
