subdomain: netbox

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

server:
  image:
    repository: netboxcommunity/netbox
    tag: v4.6.9@sha256:b1639229a0cf67052a2d53d7f7df004c840f49c9959a321bf310b6373df7240c
    pullPolicy: IfNotPresent

redis:
  image:
    repository: valkey/valkey
    tag: 9-alpine@sha256:15568b9cb7eb67f4aed4de018c23f13d344e0e6437b31fe8fb8823dc81ebb3a9
    pullPolicy: IfNotPresent

database:
  enabled: true

persistentVolumeClaims:
  - name: media
    size: 5Gi
    storageClassName: local-path
    backup: true
  - name: reports
    size: 1Gi
    storageClassName: local-path
    backup: false

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
  servicePort: 80

oidc:
  enabled: true
  redirectUris:
    - "/oauth/complete/oidc/"
  subjectMode: user_username

externalSecrets:
  - name: "{release}-secrets"
    passwords:
      - name: secret-key
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - secret-key
      - name: superuser-password
        length: 32
        encoding: hex
        allowRepeat: true
        secretKeys:
          - superuser-password
      - name: token-pepper
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - token-pepper
