subdomain: netbox

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

server:
  image:
    repository: netboxcommunity/netbox
    tag: v4.7.2@sha256:3cf9d3bd77aa186233b84d0ea1cf1755581d5e5678fa7d86ec3be62f79d0c643
    pullPolicy: IfNotPresent

redis:
  image:
    repository: valkey/valkey
    tag: 9-alpine@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11
    pullPolicy: IfNotPresent

database:
  enabled: true

persistentVolumeClaims:
  - name: media
    size: 5Gi
    storageClassName: local-path
    backup: true
  - name: reports
    size: 1Gi
    storageClassName: local-path
    backup: false

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
  servicePort: 80

oidc:
  enabled: true
  redirectUris:
    - "/oauth/complete/oidc/"
  subjectMode: user_username

externalSecrets:
  - name: "{release}-secrets"
    passwords:
      - name: secret-key
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - secret-key
      - name: superuser-password
        length: 32
        encoding: hex
        allowRepeat: true
        secretKeys:
          - superuser-password
      - name: token-pepper
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - token-pepper
