subdomain: netbox

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

server:
  image:
    repository: netboxcommunity/netbox
    tag: v4.6.5@sha256:980b4cba2c53bf806762b890e0d683eb23413330aa1f94f0c06f0cad31603f39
    pullPolicy: IfNotPresent

redis:
  image:
    repository: valkey/valkey
    tag: 9-alpine@sha256:c9b77919daeba2c02ad954d0c844cc4e7142069d177b89c5fd771f405daf9e02
    pullPolicy: IfNotPresent

database:
  enabled: true

persistentVolumeClaims:
  - name: media
    size: 5Gi
    storageClassName: local-path
    backup: true
  - name: reports
    size: 1Gi
    storageClassName: local-path
    backup: false

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
  servicePort: 80

oidc:
  enabled: true
  redirectUris:
    - "/oauth/complete/oidc/"
  subjectMode: user_username

externalSecrets:
  - name: "{release}-secrets"
    passwords:
      - name: secret-key
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - secret-key
      - name: superuser-password
        length: 32
        encoding: hex
        allowRepeat: true
        secretKeys:
          - superuser-password
      - name: token-pepper
        length: 64
        encoding: hex
        allowRepeat: true
        secretKeys:
          - token-pepper
