image:
  repository: ghcr.io/morten-olsen/health/api
  tag: latest@sha256:196f7eb390a620b2a592083c12e94babc6243dbc98cb04ae6d86ce41f9dc19e9
  pullPolicy: IfNotPresent

subdomain: health

# Deployment configuration
deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0

# Container configuration
container:
  port: 3007
  healthProbe:
    type: httpGet
    path: /healthz

# Service configuration
service:
  port: 80
  type: ClusterIP

probe:
  path: /healthz

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: false
    private: true

# Database configuration
database:
  enabled: true

# Environment variables
env:
  DATABASE_URL:
    valueFrom:
      secretKeyRef:
        name: "{release}-connection"
        key: url
