globals:
  environment: prod
  timezone: Europe/Amsterdam
  domain: olsen.cloud
image:
  repository: docker.n8n.io/n8nio/n8n
  tag: 1.113.2@sha256:4c1ba1a29b773752cb92b3ac89249a69cb95c6cb591cb7e0587cd8a78cc5fde4
  pullPolicy: IfNotPresent
subdomain: n8n
