globals:
  environment: prod
  timezone: Europe/Amsterdam
  domain: olsen.cloud
image:
  repository: docker.n8n.io/n8nio/n8n
  tag: 1.113.3@sha256:57f95a26b1b28527053fba6316d9d046395d9b4da9d0da486e838384a38fcf37
  pullPolicy: IfNotPresent
subdomain: n8n
