apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    server_url: https://{{ .Values.subdomain }}.{{ .Values.globals.domain }}
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090

    tls_cert_path: ""
    tls_key_path: ""

    noise:
      private_key_path: /var/lib/headscale/noise_private.key

    prefixes:
      v4: {{ .Values.headscale.prefixes.v4 }}
      v6: {{ .Values.headscale.prefixes.v6 }}
      allocation: sequential

    derp:
      server:
        enabled: false
      urls:
        {{- range .Values.headscale.derp.urls }}
        - {{ . }}
        {{- end }}
      auto_update_enabled: true
      update_frequency: 24h

    database:
      type: postgres
      postgres:
        host: TO_BE_REPLACED_BY_INIT
        port: 5432
        name: TO_BE_REPLACED_BY_INIT
        user: TO_BE_REPLACED_BY_INIT
        pass: TO_BE_REPLACED_BY_INIT
        max_open_conns: 10
        max_idle_conns: 10
        conn_max_idle_time_secs: 3600

    dns:
      magic_dns: {{ .Values.headscale.dns.magicDns }}
      base_domain: {{ .Values.headscale.dns.baseDomain }}
      nameservers:
        global:
          {{- range .Values.headscale.dns.nameservers.global }}
          - {{ . }}
          {{- end }}

    oidc:
      issuer: TO_BE_REPLACED_BY_INIT
      client_id: TO_BE_REPLACED_BY_INIT
      client_secret: TO_BE_REPLACED_BY_INIT

    log:
      level: info

    policy:
      mode: file
      path: ""
