globals:
  environment: prod
  timezone: Europe/Amsterdam
  domain: olsen.cloud
image:
  repository: docker.io/ckulka/baikal
  tag: 0.10.1-nginx@sha256:434bdd162247cc6aa6f878c9b4dce6216e39e79526b980453b13812d5f8ebf4b
  pullPolicy: IfNotPresent
subdomain: baikal
