image:
  repository: codeberg.org/readeck/readeck
  tag: latest@sha256:32bd82e457a3a9a3fffb161f55cfebf0fd7ffbc87ddf2fe7a321361905348f0a
  pullPolicy: IfNotPresent

subdomain: readeck

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

# Deployment configuration
deployment:
  strategy: Recreate
  replicas: 1

# Container configuration
container:
  port: 8000
  healthProbe:
    type: tcpSocket
    port: http # Use named port

# Service configuration
service:
  port: 80
  type: ClusterIP

# Volume configuration
volumes:
  - name: data
    mountPath: /readeck
    persistentVolumeClaim: data

# Persistent volume claims
persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: true

# VirtualService configuration
virtualService:
  enabled: true
  gateways:
    public: true
    private: true

# Environment variables
env:
  TZ:
    value: "{timezone}"
  READECK_SERVER_HOST: "0.0.0.0"
