when:
  - event: [cron, manual]

steps:
  renovate:
    image: code.olsen.cloud/ci/renovate:latest@sha256:cc1e28e44771eed890daf18f434d561aa24db7dcf6c4352e516869ede5bb25c5
    settings:
      token:
        from_secret: renovate_forgejo_token
