image:
  repository: ghcr.io/music-assistant/server
  tag: 2.9.5@sha256:d5f2e4e7ef2b9798b554c1ad79b0444728606d8f68f8b151f64621934d80ef65
  pullPolicy: IfNotPresent

subdomain: music-assistant

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

container:
  port: 8095
  healthProbe:
    type: tcpSocket
  securityContext:
    capabilities:
      add:
        - SYS_ADMIN
        - DAC_READ_SEARCH

service:
  port: 80

volumes:
  - name: data
    mountPath: /data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: true

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
