image:
  repository: ghcr.io/music-assistant/server
  tag: 2.8.4@sha256:f25ab51703e81e18c90d023916d2bc7c8b1ef98b99503644fc12277bacc69ecd
  pullPolicy: IfNotPresent

subdomain: music-assistant

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  hostNetwork: true

container:
  port: 8095
  healthProbe:
    type: tcpSocket
  securityContext:
    capabilities:
      add:
        - SYS_ADMIN
        - DAC_READ_SEARCH

service:
  port: 80

volumes:
  - name: data
    mountPath: /data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: true

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
