image:
  repository: ghcr.io/music-assistant/server
  tag: 2.9.11@sha256:dd0605ba528af46bb1c36ceb71fa57f5e9b23d10ec2fff787bd16495271f5681
  pullPolicy: IfNotPresent

subdomain: music-assistant

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

container:
  port: 8095
  healthProbe:
    type: tcpSocket
  securityContext:
    capabilities:
      add:
        - SYS_ADMIN
        - DAC_READ_SEARCH

service:
  port: 80

volumes:
  - name: data
    mountPath: /data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: true

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
