image:
  repository: bbernhard/signal-cli-rest-api
  tag: "0.100@sha256:2399d449123cdad56c4d859277e3b9127e1a00c4d2ab4601c239882609286cf8"
  pullPolicy: IfNotPresent

subdomain: apprise

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

command:
  - /usr/bin/signal-cli
args:
  - --config=/home/.local/share/signal-cli
  - daemon
  - --http=0.0.0.0:8080

deployment:
  strategy: Recreate
  replicas: 1

container:
  port: 8080
  healthProbe:
    type: tcpSocket

service:
  port: 80

volumes:
  - name: data
    mountPath: /home/.local/share/signal-cli
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: true

probe:
  enabled: false

virtualService:
  enabled: false

env:
  MODE: "json-rpc"
