image:
  repository: bbernhard/signal-cli-rest-api
  tag: "0.98@sha256:c51c117d030d051f0cf2ef17f2cb135f1301810f9526a224be67daded8f272d6"
  pullPolicy: IfNotPresent

subdomain: apprise

command:
  - /usr/bin/signal-cli
args:
  - --config=/home/.local/share/signal-cli
  - daemon
  - --http=0.0.0.0:8080

deployment:
  strategy: Recreate
  replicas: 1

container:
  port: 8080
  healthProbe:
    type: tcpSocket

service:
  port: 80

volumes:
  - name: data
    mountPath: /home/.local/share/signal-cli
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: true

virtualService:
  enabled: false

env:
  MODE: "json-rpc"
