image:
  repository: docker.io/eclipse-mosquitto
  tag: 2.0.22@sha256:914f529386804c8278a4e581526b9be5e1604df44b30daabc70aa97dcefe5268
  pullPolicy: IfNotPresent

subdomain: mqtt

# DNS configuration
dns:
  enabled: true
  type: A
  dnsClassRef:
    name: private-dns

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  podAnnotations:
    traffic.sidecar.istio.io/excludeInboundPorts: "1883"

container:
  ports:
    - name: tcp-mqtt
      port: 1883
  healthProbe:
    type: exec
    command:
      - sh
      - -c
      - mosquitto_pub -h localhost -p 1883 -t health/ready -m "ready" -q 0 -i readiness_client -V 5
    initialDelaySeconds: 10
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

service:
  type: LoadBalancer
  ports:
    - name: tcp-mqtt
      port: 1883
      targetPort: 1883

volumes:
  - name: config
    mountPath: /mosquitto/config
    configMap: "{release}-config"
  - name: data
    mountPath: /mosquitto/data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: true

probe:
  enabled: false  # MQTT protocol, not HTTP

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
