image:
  repository: louislam/uptime-kuma
  tag: 2@sha256:9aeb4e51d038047f414309c77a1af553281ca535723cb88907d907269d0a908e
  pullPolicy: IfNotPresent

subdomain: uptime-kuma

deployment:
  strategy: Recreate
  replicas: 1
  revisionHistoryLimit: 0

container:
  port: 3001
  healthProbe:
    type: tcpSocket

service:
  port: 80

volumes:
  - name: data
    mountPath: /app/data
    persistentVolumeClaim: data

persistentVolumeClaims:
  - name: data
    size: 1Gi
    storageClassName: local-path
    backup: true

virtualService:
  enabled: true
  gateways:
    public: false
    private: true
